version: "3"

services:
  myapi:
    restart: unless-stopped
    container_name: myapi
    image: myapi
    environment:
      - PORT=80
    ports:
      - 80:8080
      - 443:443
    build:
      context: .
      dockerfile: Dockerfile

    # networks:
    #   - application

# networks:
#   application:
